/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea9;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * 
 */
public class panel_retiro_efectivo extends javax.swing.JPanel {

    /**
     * Creates new form panel_retiro_efectivo
     */
    public panel_retiro_efectivo() {
        initComponents();
        
        lblRetiroEfectivo.setVisible(false);
        lblRetiroEfectivoDos.setVisible(false);
        btnSalir.setVisible(false);
        
        File file = new File("img/panel_inicio.png");
        Resizable resizable = new Resizable();
        try {
            BufferedImage imagen =  ImageIO.read(file);
            BufferedImage imagenredimensionada = resizable.resize(imagen, 630, 533);
            setBorder(new ImagenBorder(imagenredimensionada));
            
            System.out.println("Imagen cargada");
        } catch (IOException ex) {
            System.err.println("Error al cargar imagen " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMontoRetirar = new javax.swing.JLabel();
        btn50 = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblRetiroEfectivo = new javax.swing.JLabel();
        lblRetiroEfectivoDos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblMontoRetirar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMontoRetirar.setText("SELECCIONE EL MONTO QUE DESEA RETIRAR");

        btn50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn50.setText("10");

        btn100.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn100.setText("100");

        btn200.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn200.setText("20");

        btn500.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn500.setText("200");

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");

        lblRetiroEfectivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRetiroEfectivo.setText("RETIRO DE EFECTIVO EXITOSO");

        lblRetiroEfectivoDos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRetiroEfectivoDos.setText("TOME SU EFECTIVO!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(lblMontoRetirar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn100))
                            .addGap(171, 171, 171)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn500))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblRetiroEfectivo)
                            .addComponent(lblRetiroEfectivoDos)
                            .addComponent(btnSalir))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(lblMontoRetirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblRetiroEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRetiroEfectivoDos)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn200, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn50, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn100;
    public javax.swing.JButton btn200;
    public javax.swing.JButton btn50;
    public javax.swing.JButton btn500;
    public javax.swing.JButton btnSalir;
    public javax.swing.JLabel lblMontoRetirar;
    public javax.swing.JLabel lblRetiroEfectivo;
    public javax.swing.JLabel lblRetiroEfectivoDos;
    // End of variables declaration//GEN-END:variables
}
